2019-07-28 17:56:45,701  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://121.13.252.61:41564HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x06282C30>, 'Connection to 121.13.252.61 timed out. (connect timeout=5)'))
2019-07-28 17:56:45,951  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://117.90.6.92:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x062A1B70>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-28 17:56:47,772  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://121.232.194.238:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x06297BF0>, 'Connection to 121.232.194.238 timed out. (connect timeout=5)'))
2019-07-28 17:56:50,026  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://112.17.121.88:8060HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProtocolError('Connection aborted.', BadStatusLine('<html>\r\n')))
2019-07-28 17:56:50,704  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://117.90.5.55:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x062AD350>, 'Connection to 117.90.5.55 timed out. (connect timeout=5)'))
2019-07-28 17:56:50,955  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://115.219.35.59:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x062AD990>, 'Connection to 115.219.35.59 timed out. (connect timeout=5)'))
2019-07-28 17:56:51,287  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://123.57.61.38:8118HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections')))
2019-07-28 17:56:52,085  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://113.121.22.209:9999HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x071BD8D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-28 17:56:52,092  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://47.95.249.140:8118HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections')))
2019-07-28 17:56:52,181  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://120.79.64.147:8118HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections')))
2019-07-28 17:56:54,263  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://114.230.69.193:9999HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x071CBF90>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-28 17:56:55,030  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://121.232.199.9:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x062A1830>, 'Connection to 121.232.199.9 timed out. (connect timeout=5)'))
2019-07-28 17:56:55,353  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://117.90.5.25:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x071CBBB0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-28 17:56:55,707  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://112.111.109.65:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x071BD4D0>, 'Connection to 112.111.109.65 timed out. (connect timeout=5)'))
2019-07-28 17:56:56,102  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://117.90.137.139:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x06282AD0>, 'Connection to 117.90.137.139 timed out. (connect timeout=5)'))
2019-07-28 17:56:56,166  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://117.87.176.148:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x071BD570>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-28 17:56:56,291  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://202.120.38.131:80HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x071B1930>, 'Connection to 202.120.38.131 timed out. (connect timeout=5)'))
2019-07-28 17:56:56,376  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://180.118.134.51:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x071D8ED0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-28 17:56:56,475  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://121.232.194.171:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x071D8F10>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-28 17:56:57,138  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://193.112.128.212:8118HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out')))
2019-07-28 17:56:57,184  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://171.13.103.27:9999HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x071B1510>, 'Connection to 171.13.103.27 timed out. (connect timeout=5)'))
2019-07-28 17:56:57,471  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://121.232.194.33:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x071CB5D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-28 17:56:59,520  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://116.62.198.43:8080HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 400 Bad Request')))
2019-07-28 17:56:59,614  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://47.107.160.99:8118HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections')))
2019-07-28 17:57:01,105  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://219.159.38.206:56210HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x071E6710>, 'Connection to 219.159.38.206 timed out. (connect timeout=5)'))
2019-07-28 17:57:01,170  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://59.62.35.186:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x071E6D50>, 'Connection to 59.62.35.186 timed out. (connect timeout=5)'))
2019-07-28 17:57:01,249  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://193.112.12.148:8080HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1039: The handshake operation timed out')))
2019-07-28 17:57:01,295  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://114.235.23.131:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x084E4570>, 'Connection to 114.235.23.131 timed out. (connect timeout=5)'))
2019-07-28 17:57:01,480  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://119.254.94.114:34422HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x062975B0>, 'Connection to 119.254.94.114 timed out. (connect timeout=5)'))
2019-07-28 17:57:02,188  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://117.90.1.61:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x071BD5B0>, 'Connection to 117.90.1.61 timed out. (connect timeout=5)'))
2019-07-28 17:57:02,408  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://183.129.207.86:14002HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out')))
2019-07-28 17:57:02,476  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://121.232.148.36:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x071D87D0>, 'Connection to 121.232.148.36 timed out. (connect timeout=5)'))
2019-07-28 17:57:02,602  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://180.118.128.24:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x084F1C10>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-28 17:57:03,303  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://121.232.148.166:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x071E6B10>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-28 17:57:04,332  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://123.207.247.86:9999HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProtocolError('Connection aborted.', BadStatusLine('<html>\r\n')))
2019-07-28 17:57:04,684  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://115.218.212.53:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x084F1A90>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-28 17:57:05,194  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://183.129.207.80:13516HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out')))
2019-07-28 17:57:05,457  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://180.104.62.98:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x071D86F0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-28 17:57:06,108  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://183.129.244.16:11006HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x071E65B0>, 'Connection to 183.129.244.16 timed out. (connect timeout=5)'))
2019-07-28 17:57:06,173  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://121.232.148.85:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x071B18B0>, 'Connection to 121.232.148.85 timed out. (connect timeout=5)'))
2019-07-28 17:57:06,187  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://117.90.4.114:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', ConnectionAbortedError(10053, '你的主机中的软件中止了一个已建立的连接。', None, 10053, None)))
2019-07-28 17:57:06,253  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://114.234.82.198:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x071CBC90>, 'Connection to 114.234.82.198 timed out. (connect timeout=5)'))
2019-07-28 17:57:06,298  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://115.210.27.113:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x084F1810>, 'Connection to 115.210.27.113 timed out. (connect timeout=5)'))
2019-07-28 17:57:06,848  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://125.117.134.235:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x084F91D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-28 17:57:07,411  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://221.206.100.133:54781HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x071E6450>, 'Connection to 221.206.100.133 timed out. (connect timeout=5)'))
2019-07-28 17:57:07,479  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://112.111.118.60:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x084F96F0>, 'Connection to 112.111.118.60 timed out. (connect timeout=5)'))
2019-07-28 17:57:07,606  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://58.22.204.118:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x084F9B50>, 'Connection to 58.22.204.118 timed out. (connect timeout=5)'))
2019-07-28 17:57:07,674  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://183.129.207.80:12834HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out')))
2019-07-28 17:57:08,019  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://47.100.21.174:8118HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections')))
2019-07-28 17:57:08,307  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://112.111.99.217:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x084F1970>, 'Connection to 112.111.99.217 timed out. (connect timeout=5)'))
2019-07-28 17:57:08,388  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://193.112.38.11:8118HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections')))
2019-07-28 17:57:08,520  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://180.119.68.50:9999HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x084E45B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-28 17:57:09,687  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://221.7.211.246:51864HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x071BD050>, 'Connection to 221.7.211.246 timed out. (connect timeout=5)'))
2019-07-28 17:57:09,992  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://106.14.206.26:8118HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections')))
2019-07-28 17:57:10,513  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://193.112.12.148:8080HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out')))
2019-07-28 17:57:10,744  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://183.147.31.60:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x085065F0>, 'Connection to 183.147.31.60 timed out. (connect timeout=5)'))
2019-07-28 17:57:11,192  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://115.218.210.106:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x084F1630>, 'Connection to 115.218.210.106 timed out. (connect timeout=5)'))
2019-07-28 17:57:11,257  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://117.90.2.215:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x071E66F0>, 'Connection to 117.90.2.215 timed out. (connect timeout=5)'))
2019-07-28 17:57:11,302  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://163.125.223.119:8118HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x085153F0>, 'Connection to 163.125.223.119 timed out. (connect timeout=5)'))
2019-07-28 17:57:11,378  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://47.107.186.18:8118HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections')))
2019-07-28 17:57:11,445  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://101.132.164.113:8118HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections')))
2019-07-28 17:57:12,351  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://47.93.36.195:8118HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections')))
2019-07-28 17:57:12,483  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://58.22.210.111:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x071BDD90>, 'Connection to 58.22.210.111 timed out. (connect timeout=5)'))
2019-07-28 17:57:12,563  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://121.232.194.196:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x062ADBD0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-28 17:57:12,612  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://175.42.68.110:9999HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x062A1050>, 'Connection to 175.42.68.110 timed out. (connect timeout=5)'))
2019-07-28 17:57:12,680  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://175.42.169.235:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x071B12B0>, 'Connection to 175.42.169.235 timed out. (connect timeout=5)'))
2019-07-28 17:57:13,031  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://219.159.38.200:56210HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-28 17:57:13,065  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://183.129.207.80:12520HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out')))
2019-07-28 17:57:13,403  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://123.206.30.254:8118HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out')))
2019-07-28 17:57:13,524  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://106.14.160.134:80HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x09FE4070>, 'Connection to 106.14.160.134 timed out. (connect timeout=5)'))
2019-07-28 17:57:13,697  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://117.90.5.24:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x085159F0>, 'Connection to 117.90.5.24 timed out. (connect timeout=5)'))
2019-07-28 17:57:13,734  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://121.232.194.171:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x084F9370>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-28 17:57:13,824  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://115.218.208.180:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09FFA970>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-28 17:57:14,156  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://117.90.6.148:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x084F1510>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-28 17:57:14,690  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://114.234.80.241:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x09FE47B0>, 'Connection to 114.234.80.241 timed out. (connect timeout=5)'))
2019-07-28 17:57:14,995  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://60.205.229.126:80HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x084E4A30>, 'Connection to 60.205.229.126 timed out. (connect timeout=5)'))
2019-07-28 17:57:15,087  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://120.25.90.253:8118HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', ConnectionAbortedError(10053, '你的主机中的软件中止了一个已建立的连接。', None, 10053, None)))
2019-07-28 17:57:15,183  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://118.122.114.249:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-28 17:57:15,310  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://113.121.41.75:9999HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09FFA930>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-28 17:57:15,476  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://47.94.221.41:8118HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections')))
2019-07-28 17:57:15,516  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://183.129.244.16:13357HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x071CB790>, 'Connection to 183.129.244.16 timed out. (connect timeout=5)'))
2019-07-28 17:57:15,748  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://112.111.108.252:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x084F1F10>, 'Connection to 112.111.108.252 timed out. (connect timeout=5)'))
2019-07-28 17:57:16,196  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://47.98.237.129:80HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x09FF1370>, 'Connection to 47.98.237.129 timed out. (connect timeout=5)'))
2019-07-28 17:57:16,297  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://193.112.38.11:8118HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections')))
2019-07-28 17:57:16,305  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://49.81.125.63:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x084F1550>, 'Connection to 49.81.125.63 timed out. (connect timeout=5)'))
2019-07-28 17:57:16,591  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://180.118.134.91:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x084F1470>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-28 17:57:17,302  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://121.232.194.97:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x084E4890>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-28 17:57:17,398  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://183.129.207.80:12834HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out')))
2019-07-28 17:57:17,567  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://112.111.97.101:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x084F1FF0>, 'Connection to 112.111.97.101 timed out. (connect timeout=5)'))
2019-07-28 17:57:18,068  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://175.44.155.84:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x071B1F10>, 'Connection to 175.44.155.84 timed out. (connect timeout=5)'))
2019-07-28 17:57:18,387  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://211.159.219.225:8118HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections')))
2019-07-28 17:57:18,528  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://117.87.178.147:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0A005170>, 'Connection to 117.87.178.147 timed out. (connect timeout=5)'))
2019-07-28 17:57:18,591  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://117.41.38.18:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', ConnectionAbortedError(10053, '你的主机中的软件中止了一个已建立的连接。', None, 10053, None)))
2019-07-28 17:57:18,703  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://219.159.38.206:56210HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x08515AD0>, 'Connection to 219.159.38.206 timed out. (connect timeout=5)'))
2019-07-28 17:57:18,738  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://61.176.223.7:58822HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x09FE40F0>, 'Connection to 61.176.223.7 timed out. (connect timeout=5)'))
2019-07-28 17:57:18,827  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://221.206.100.133:54781HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x084F92D0>, 'Connection to 221.206.100.133 timed out. (connect timeout=5)'))
2019-07-28 17:57:19,125  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://61.164.39.68:53281HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0A005670>, 'Connection to 61.164.39.68 timed out. (connect timeout=5)'))
2019-07-28 17:57:19,207  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://134.175.55.15:8888HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections')))
2019-07-28 17:57:19,231  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://175.44.152.131:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AD41530>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-28 17:57:19,452  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://47.100.21.174:8021HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))
2019-07-28 17:57:19,658  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://125.110.89.61:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09FFA770>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-28 17:57:19,697  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://61.164.39.66:53281HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x062AD4B0>, 'Connection to 61.164.39.66 timed out. (connect timeout=5)'))
2019-07-28 17:57:20,186  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://117.87.178.68:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x085155B0>, 'Connection to 117.87.178.68 timed out. (connect timeout=5)'))
2019-07-28 17:57:20,503  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://47.93.18.195:80HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out')))
2019-07-28 17:57:20,562  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://183.129.207.80:12655HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out')))
2019-07-28 17:57:20,794  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://183.129.207.80:12889HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out')))
2019-07-28 17:57:21,302  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://112.111.116.42:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x09FE40D0>, 'Connection to 112.111.116.42 timed out. (connect timeout=5)'))
2019-07-28 17:57:21,446  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://183.129.207.80:12085HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out')))
2019-07-28 17:57:21,595  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://117.90.252.221:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x09FF1130>, 'Connection to 117.90.252.221 timed out. (connect timeout=5)'))
2019-07-28 17:57:22,306  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://121.232.194.91:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0A0158D0>, 'Connection to 121.232.194.91 timed out. (connect timeout=5)'))
2019-07-28 17:57:22,404  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://47.93.18.195:80HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x09FF1A50>, 'Connection to 47.93.18.195 timed out. (connect timeout=5)'))
2019-07-28 17:57:22,570  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://175.44.151.198:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0AD41170>, 'Connection to 175.44.151.198 timed out. (connect timeout=5)'))
2019-07-28 17:57:22,707  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://117.91.255.20:9999HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x062AD5D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-28 17:57:23,168  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://182.92.113.183:8118HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))
2019-07-28 17:57:23,596  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://49.70.33.110:9999HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x071B1090>, 'Connection to 49.70.33.110 timed out. (connect timeout=5)'))
2019-07-28 17:57:23,740  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://221.6.32.206:41816HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out')))
2019-07-28 17:57:23,741  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://180.118.134.66:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0AD418D0>, 'Connection to 180.118.134.66 timed out. (connect timeout=5)'))
2019-07-28 17:57:23,827  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://183.129.207.80:12806HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-28 17:57:23,874  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://183.129.207.80:12520HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out')))
2019-07-28 17:57:24,234  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://115.219.32.108:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x09FFAC30>, 'Connection to 115.219.32.108 timed out. (connect timeout=5)'))
2019-07-28 17:57:24,456  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://123.101.215.202:9999HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x08515BD0>, 'Connection to 123.101.215.202 timed out. (connect timeout=5)'))
2019-07-28 17:57:24,662  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://175.44.149.166:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0A0054B0>, 'Connection to 175.44.149.166 timed out. (connect timeout=5)'))
2019-07-28 17:57:24,701  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://175.44.150.223:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0AD417D0>, 'Connection to 175.44.150.223 timed out. (connect timeout=5)'))
2019-07-28 17:57:24,734  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://116.208.54.212:9999HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x084E4830>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-28 17:57:25,190  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://218.27.84.219:8118HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x08515170>, 'Connection to 218.27.84.219 timed out. (connect timeout=5)'))
2019-07-28 17:57:25,345  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://94.191.102.78:8081HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 405 Method Not Allowed')))
2019-07-28 17:57:25,359  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://117.87.178.93:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x071CBEF0>, 'Connection to 117.87.178.93 timed out. (connect timeout=5)'))
2019-07-28 17:57:25,507  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://122.242.135.71:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x09FFA390>, 'Connection to 122.242.135.71 timed out. (connect timeout=5)'))
2019-07-28 17:57:25,611  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://183.129.207.80:12520HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out')))
2019-07-28 17:57:25,798  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://106.14.160.134:80HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0AD41490>, 'Connection to 106.14.160.134 timed out. (connect timeout=5)'))
2019-07-28 17:57:25,906  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://175.44.109.70:9999HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0A0159D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-28 17:57:25,950  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://115.28.148.192:8118HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections')))
2019-07-28 17:57:25,971  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://47.94.104.204:8118HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections')))
2019-07-28 17:57:26,305  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://175.44.157.171:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x084F9F10>, 'Connection to 175.44.157.171 timed out. (connect timeout=5)'))
2019-07-28 17:57:26,450  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://219.159.38.202:56210HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x084F9A90>, 'Connection to 219.159.38.202 timed out. (connect timeout=5)'))
2019-07-28 17:57:26,488  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://121.236.8.116:9999HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0A005370>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-28 17:57:26,503  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://221.2.155.35:8060HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-28 17:57:27,353  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://221.6.32.206:41816HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out')))
2019-07-28 17:57:27,711  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://180.118.134.29:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x09FF17F0>, 'Connection to 180.118.134.29 timed out. (connect timeout=5)'))
2019-07-28 17:57:28,173  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://180.118.86.185:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x08506930>, 'Connection to 180.118.86.185 timed out. (connect timeout=5)'))
2019-07-28 17:57:28,746  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://175.161.17.139:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0A005DF0>, 'Connection to 175.161.17.139 timed out. (connect timeout=5)'))
2019-07-28 17:57:28,830  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://203.110.164.139:52144HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x08515250>, 'Connection to 203.110.164.139 timed out. (connect timeout=5)'))
2019-07-28 17:57:28,877  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://115.218.212.239:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x084E4AF0>, 'Connection to 115.218.212.239 timed out. (connect timeout=5)'))
2019-07-28 17:57:29,239  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://219.159.38.197:56210HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x09FE4670>, 'Connection to 219.159.38.197 timed out. (connect timeout=5)'))
2019-07-28 17:57:29,272  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://117.90.4.107:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09FFAD70>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-28 17:57:29,459  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://112.85.175.215:9999HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x071CBDD0>, 'Connection to 112.85.175.215 timed out. (connect timeout=5)'))
2019-07-28 17:57:29,666  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://106.15.42.179:33543HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x084F9BF0>, 'Connection to 106.15.42.179 timed out. (connect timeout=5)'))
2019-07-28 17:57:29,704  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://125.110.82.142:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x084F16D0>, 'Connection to 125.110.82.142 timed out. (connect timeout=5)'))
2019-07-28 17:57:29,859  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://117.90.6.88:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x071E6BF0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-28 17:57:30,004  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://121.232.194.111:9999HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AD414B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-28 17:57:30,297  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://136.228.128.14:61158HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-28 17:57:30,350  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://116.208.55.75:9999HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x09FF10D0>, 'Connection to 116.208.55.75 timed out. (connect timeout=5)'))
2019-07-28 17:57:30,414  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://47.98.174.153:8118HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections')))
2019-07-28 17:57:30,512  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://112.111.99.161:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x084E4810>, 'Connection to 112.111.99.161 timed out. (connect timeout=5)'))
2019-07-28 17:57:30,616  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://117.87.176.140:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x084F1630>, 'Connection to 117.87.176.140 timed out. (connect timeout=5)'))
2019-07-28 17:57:30,803  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://49.81.125.72:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x08515450>, 'Connection to 49.81.125.72 timed out. (connect timeout=5)'))
2019-07-28 17:57:30,975  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://117.87.178.207:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x084F1F30>, 'Connection to 117.87.178.207 timed out. (connect timeout=5)'))
2019-07-28 17:57:30,978  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://183.147.223.50:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09FF1290>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-28 17:57:31,310  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://120.83.102.211:9999HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x09FFA270>, 'Connection to 120.83.102.211 timed out. (connect timeout=5)'))
2019-07-28 17:57:31,438  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://180.104.62.155:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0A005710>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-28 17:57:31,509  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://123.163.8.159:9999HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0A015DF0>, 'Connection to 123.163.8.159 timed out. (connect timeout=5)'))
2019-07-28 17:57:31,547  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://120.25.203.182:7777HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out')))
2019-07-28 17:57:32,393  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://115.53.22.51:9999HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x084F9CF0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-28 17:57:32,408  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://121.232.148.56:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out')))
2019-07-28 17:57:32,683  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://121.232.199.42:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0A015EB0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-28 17:57:32,716  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://112.111.118.169:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x08506D30>, 'Connection to 112.111.118.169 timed out. (connect timeout=5)'))
2019-07-28 17:57:32,772  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://47.107.160.99:8118HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections')))
2019-07-28 17:57:33,833  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://180.118.247.25:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x084F9E90>, 'Connection to 180.118.247.25 timed out. (connect timeout=5)'))
2019-07-28 17:57:33,996  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://120.132.18.138:8888HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Forwarding failure')))
2019-07-28 17:57:34,244  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://218.27.84.219:8118HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x084E4450>, 'Connection to 218.27.84.219 timed out. (connect timeout=5)'))
2019-07-28 17:57:34,275  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://61.178.149.237:59042HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x08515A70>, 'Connection to 61.178.149.237 timed out. (connect timeout=5)'))
2019-07-28 17:57:34,463  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://175.42.168.171:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0A005EF0>, 'Connection to 175.42.168.171 timed out. (connect timeout=5)'))
2019-07-28 17:57:34,708  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://180.104.63.37:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x071E6290>, 'Connection to 180.104.63.37 timed out. (connect timeout=5)'))
2019-07-28 17:57:34,733  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://59.108.125.241:8080HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 400 Bad Request')))
2019-07-28 17:57:34,814  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://111.230.254.195:8118HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', ConnectionAbortedError(10053, '你的主机中的软件中止了一个已建立的连接。', None, 10053, None)))
2019-07-28 17:57:34,873  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://139.196.73.149:8118HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections')))
2019-07-28 17:57:35,007  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://117.91.254.235:9999HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x071B1A50>, 'Connection to 117.91.254.235 timed out. (connect timeout=5)'))
2019-07-28 17:57:35,386  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://58.22.209.123:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09FE4A90>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-28 17:57:35,420  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://117.90.2.118:9999HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x071CB370>, 'Connection to 117.90.2.118 timed out. (connect timeout=5)'))
2019-07-28 17:57:35,515  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://106.4.137.167:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x09FFACB0>, 'Connection to 106.4.137.167 timed out. (connect timeout=5)'))
2019-07-28 17:57:35,532  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://47.94.136.5:8118HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections')))
2019-07-28 17:57:35,620  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://45.125.32.178:3128HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x084F1570>, 'Connection to 45.125.32.178 timed out. (connect timeout=5)'))
2019-07-28 17:57:35,980  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://112.111.217.70:9999HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0A015CB0>, 'Connection to 112.111.217.70 timed out. (connect timeout=5)'))
2019-07-28 17:57:35,982  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://121.232.148.34:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x071B1750>, 'Connection to 121.232.148.34 timed out. (connect timeout=5)'))
2019-07-28 17:57:36,105  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://117.87.177.53:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0AD41EB0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-28 17:57:36,192  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://59.62.6.151:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x09FF1A70>, 'Connection to 59.62.6.151 timed out. (connect timeout=5)'))
2019-07-28 17:57:36,209  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://123.57.84.116:8118HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections')))
2019-07-28 17:57:36,441  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://112.111.110.217:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0AD41BB0>, 'Connection to 112.111.110.217 timed out. (connect timeout=5)'))
2019-07-28 17:57:36,551  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://60.191.57.78:14051HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out')))
2019-07-28 17:57:37,038  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://193.112.38.11:8118HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections')))
2019-07-28 17:57:37,130  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://120.76.191.177:8118HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', ConnectionAbortedError(10053, '你的主机中的软件中止了一个已建立的连接。', None, 10053, None)))
2019-07-28 17:57:37,396  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://222.189.144.192:9999HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x084F9370>, 'Connection to 222.189.144.192 timed out. (connect timeout=5)'))
2019-07-28 17:57:37,453  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://60.191.57.78:14051HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out')))
2019-07-28 17:57:37,719  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://117.90.137.93:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x071BDDD0>, 'Connection to 117.90.137.93 timed out. (connect timeout=5)'))
2019-07-28 17:57:37,777  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://175.44.158.131:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x09FF1610>, 'Connection to 175.44.158.131 timed out. (connect timeout=5)'))
2019-07-28 17:57:38,247  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://115.239.24.207:9999HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x071BD710>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-28 17:57:38,516  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://125.123.138.31:9999HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x084F9BB0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-28 17:57:39,380  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://114.234.80.7:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x062A1DD0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-28 17:57:39,467  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://61.164.39.66:53281HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x084E4950>, 'Connection to 61.164.39.66 timed out. (connect timeout=5)'))
2019-07-28 17:57:39,534  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://60.191.57.78:12178HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', ConnectionAbortedError(10053, '你的主机中的软件中止了一个已建立的连接。', None, 10053, None)))
2019-07-28 17:57:39,877  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://61.164.39.66:53281HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x084F99D0>, 'Connection to 61.164.39.66 timed out. (connect timeout=5)'))
2019-07-28 17:57:39,908  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://118.89.216.43:8888HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 400 Bad Request')))
2019-07-28 17:57:40,012  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://118.24.156.214:8118HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x06297EF0>, 'Connection to 118.24.156.214 timed out. (connect timeout=5)'))
2019-07-28 17:57:40,425  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://175.44.152.84:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x09FFA9B0>, 'Connection to 175.44.152.84 timed out. (connect timeout=5)'))
2019-07-28 17:57:40,508  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://111.230.99.192:8118HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections')))
2019-07-28 17:57:40,538  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://219.159.38.208:56210HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0389FB10>, 'Connection to 219.159.38.208 timed out. (connect timeout=5)'))
2019-07-28 17:57:40,988  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://59.62.7.47:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0A0051F0>, 'Connection to 59.62.7.47 timed out. (connect timeout=5)'))
2019-07-28 17:57:41,029  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://183.129.207.81:12655HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out')))
2019-07-28 17:57:41,112  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://123.163.96.17:9999HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x062ADEB0>, 'Connection to 123.163.96.17 timed out. (connect timeout=5)'))
2019-07-28 17:57:41,214  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://123.132.232.254:61017HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x071E6C10>, 'Connection to 123.132.232.254 timed out. (connect timeout=5)'))
2019-07-28 17:57:41,444  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://125.108.120.203:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x071B1470>, 'Connection to 125.108.120.203 timed out. (connect timeout=5)'))
2019-07-28 17:57:41,554  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://117.87.178.14:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x084F9CD0>, 'Connection to 117.87.178.14 timed out. (connect timeout=5)'))
2019-07-28 17:57:41,931  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://125.117.133.148:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x071E6830>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-28 17:57:42,457  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://112.244.228.232:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x09FFA4F0>, 'Connection to 112.244.228.232 timed out. (connect timeout=5)'))
2019-07-28 17:57:42,583  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://114.234.81.137:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09FFA670>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-28 17:57:42,781  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://121.13.252.58:41564HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x071E6950>, 'Connection to 121.13.252.58 timed out. (connect timeout=5)'))
2019-07-28 17:57:43,519  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://58.22.208.102:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x071D87B0>, 'Connection to 58.22.208.102 timed out. (connect timeout=5)'))
2019-07-28 17:57:44,384  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://45.125.32.178:3128HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0A005190>, 'Connection to 45.125.32.178 timed out. (connect timeout=5)'))
2019-07-28 17:57:44,537  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://202.120.38.131:80HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x09FF1870>, 'Connection to 202.120.38.131 timed out. (connect timeout=5)'))
2019-07-28 17:57:44,951  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://221.6.139.154:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out')))
2019-07-28 17:57:45,016  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://120.83.103.105:9999HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x084E4430>, 'Connection to 120.83.103.105 timed out. (connect timeout=5)'))
2019-07-28 17:57:45,512  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://175.44.154.136:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x084F9CB0>, 'Connection to 175.44.154.136 timed out. (connect timeout=5)'))
2019-07-28 17:57:45,541  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://114.235.22.30:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x062A1970>, 'Connection to 114.235.22.30 timed out. (connect timeout=5)'))
2019-07-28 17:57:45,992  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://61.183.233.6:54896HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x09FE40D0>, 'Connection to 61.183.233.6 timed out. (connect timeout=5)'))
2019-07-28 17:57:46,179  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://125.71.212.13:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out')))
2019-07-28 17:57:46,217  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://61.164.39.66:53281HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0389FF90>, 'Connection to 61.164.39.66 timed out. (connect timeout=5)'))
2019-07-28 17:57:46,934  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://59.37.33.62:50686HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x071CB4B0>, 'Connection to 59.37.33.62 timed out. (connect timeout=5)'))
2019-07-28 17:57:47,506  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://183.129.207.80:12777HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out')))
2019-07-28 17:57:47,586  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://61.164.39.67:53281HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x09FFA370>, 'Connection to 61.164.39.67 timed out. (connect timeout=5)'))
2019-07-28 17:57:47,651  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://101.132.164.113:8118HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections')))
2019-07-28 17:57:47,785  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://58.22.209.242:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x062A1A50>, 'Connection to 58.22.209.242 timed out. (connect timeout=5)'))
2019-07-28 17:57:48,523  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://175.44.155.92:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0A015570>, 'Connection to 175.44.155.92 timed out. (connect timeout=5)'))
2019-07-28 17:57:49,389  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://58.22.210.83:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x06297B90>, 'Connection to 58.22.210.83 timed out. (connect timeout=5)'))
2019-07-28 17:57:49,541  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://175.42.68.66:9999HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x071B10D0>, 'Connection to 175.42.68.66 timed out. (connect timeout=5)'))
2019-07-28 17:57:49,622  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://112.111.116.6:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', ConnectionAbortedError(10053, '你的主机中的软件中止了一个已建立的连接。', None, 10053, None)))
2019-07-28 17:57:49,998  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://183.129.244.16:11389HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out')))
2019-07-28 17:57:50,019  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://123.163.122.171:9999HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x09FE4C10>, 'Connection to 123.163.122.171 timed out. (connect timeout=5)'))
2019-07-28 17:57:50,516  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://58.22.222.31:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x09FF1290>, 'Connection to 58.22.222.31 timed out. (connect timeout=5)'))
2019-07-28 17:57:50,546  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://117.87.178.152:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0A015C10>, 'Connection to 117.87.178.152 timed out. (connect timeout=5)'))
2019-07-28 17:57:51,182  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://218.95.50.31:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x09FE4050>, 'Connection to 218.95.50.31 timed out. (connect timeout=5)'))
2019-07-28 17:57:51,224  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://219.159.38.208:56210HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x084F9CF0>, 'Connection to 219.159.38.208 timed out. (connect timeout=5)'))
2019-07-28 17:57:51,938  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://61.164.39.68:53281HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x084F93D0>, 'Connection to 61.164.39.68 timed out. (connect timeout=5)'))
2019-07-28 17:57:52,511  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://117.90.3.237:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0A005F50>, 'Connection to 117.90.3.237 timed out. (connect timeout=5)'))
2019-07-28 17:57:52,599  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://118.24.61.165:8118HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections')))
2019-07-28 17:57:52,655  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://171.80.1.182:9999HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x09FFAC90>, 'Connection to 171.80.1.182 timed out. (connect timeout=5)'))
2019-07-28 17:57:54,545  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://163.204.93.46:9999HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x071B1790>, 'Connection to 163.204.93.46 timed out. (connect timeout=5)'))
2019-07-28 17:57:54,637  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://120.25.90.253:8118HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections')))
2019-07-28 17:57:55,209  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://49.87.110.91:9999HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0A015770>, 'Connection to 49.87.110.91 timed out. (connect timeout=5)'))
2019-07-28 17:57:55,520  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://125.110.64.117:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x071B1670>, 'Connection to 125.110.64.117 timed out. (connect timeout=5)'))
2019-07-28 17:57:55,549  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://117.87.177.38:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x09FFA5F0>, 'Connection to 117.87.177.38 timed out. (connect timeout=5)'))
2019-07-28 17:57:55,645  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://39.108.219.137:8118HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', ConnectionAbortedError(10053, '你的主机中的软件中止了一个已建立的连接。', None, 10053, None)))
2019-07-28 17:57:56,186  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://175.44.108.124:9999HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x09FFA290>, 'Connection to 175.44.108.124 timed out. (connect timeout=5)'))
2019-07-28 17:57:56,227  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://125.110.75.26:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0389F9F0>, 'Connection to 125.110.75.26 timed out. (connect timeout=5)'))
2019-07-28 17:57:56,562  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://124.47.7.38:80HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out')))
2019-07-28 17:57:56,942  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://122.243.12.171:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x062AD150>, 'Connection to 122.243.12.171 timed out. (connect timeout=5)'))
2019-07-28 17:57:57,659  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://175.44.150.171:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x084F9050>, 'Connection to 175.44.150.171 timed out. (connect timeout=5)'))
2019-07-28 17:57:58,256  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://61.183.176.122:57210HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1039: The handshake operation timed out')))
2019-07-28 17:57:59,641  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://221.2.174.3:8060HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x062A1670>, 'Connection to 221.2.174.3 timed out. (connect timeout=5)'))
2019-07-28 17:58:00,213  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://27.203.165.98:8060HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x06297EF0>, 'Connection to 27.203.165.98 timed out. (connect timeout=5)'))
2019-07-28 17:58:01,189  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://112.111.97.241:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0A015CD0>, 'Connection to 112.111.97.241 timed out. (connect timeout=5)'))
2019-07-28 17:58:01,565  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://211.101.154.105:43598HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x062A1410>, 'Connection to 211.101.154.105 timed out. (connect timeout=5)'))
2019-07-28 17:58:01,589  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://123.206.54.52:8118HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections')))
2019-07-28 17:58:01,946  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://114.235.22.54:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x084E44D0>, 'Connection to 114.235.22.54 timed out. (connect timeout=5)'))
2019-07-28 17:58:02,289  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://180.118.128.129:9999HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x062ADAF0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-28 17:58:02,375  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://123.207.247.86:9999HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProtocolError('Connection aborted.', BadStatusLine('<html>\r\n')))
2019-07-28 17:58:02,663  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://117.87.177.225:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x09FFAC50>, 'Connection to 117.87.177.225 timed out. (connect timeout=5)'))
2019-07-28 17:58:03,260  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://219.159.38.206:56210HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x09FFA770>, 'Connection to 219.159.38.206 timed out. (connect timeout=5)'))
2019-07-28 17:58:04,644  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://175.44.151.21:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x09FE4030>, 'Connection to 175.44.151.21 timed out. (connect timeout=5)'))
2019-07-28 17:58:05,218  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://115.218.208.59:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0A015DB0>, 'Connection to 115.218.208.59 timed out. (connect timeout=5)'))
2019-07-28 17:58:06,592  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://175.44.108.58:9999HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x071D8B10>, 'Connection to 175.44.108.58 timed out. (connect timeout=5)'))
2019-07-28 17:58:06,949  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://120.132.18.138:8888HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0389F130>, 'Connection to 120.132.18.138 timed out. (connect timeout=5)'))
2019-07-28 17:58:07,378  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://59.32.37.105:3128HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x062A1E90>, 'Connection to 59.32.37.105 timed out. (connect timeout=5)'))
2019-07-28 17:58:07,669  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://45.125.32.181:3128HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x084E42F0>, 'Connection to 45.125.32.181 timed out. (connect timeout=5)'))
2019-07-28 17:58:08,822  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://114.234.81.69:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x071D8070>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-28 17:58:09,651  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://118.187.58.35:53281HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x062A11B0>, 'Connection to 118.187.58.35 timed out. (connect timeout=5)'))
2019-07-28 17:58:11,598  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://183.129.207.80:12085HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x062AD9F0>, 'Connection to 183.129.207.80 timed out. (connect timeout=5)'))
2019-07-28 17:58:11,724  visitors_in_thread/visitors_in_thread.py:109  ip不可用：http://125.71.212.25:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
