2019-07-28 18:47:45,381  visitors_in_thread1/visitors_in_thread1.py:98  ip不可用：https://114.107.150.5:34070HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out')))
2019-07-28 18:48:36,554  visitors_in_thread1/visitors_in_thread1.py:98  ip不可用：https://49.86.179.227:46007HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x041F5BB0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-28 18:48:50,553  visitors_in_thread1/visitors_in_thread1.py:98  ip不可用：https://106.58.153.103:20606HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out')))
2019-07-28 18:49:00,005  visitors_in_thread1/visitors_in_thread1.py:98  ip不可用：https://49.86.179.227:46007HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x12543750>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-28 18:49:04,478  visitors_in_thread1/visitors_in_thread1.py:98  ip不可用：https://115.202.92.161:46927HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out')))
2019-07-28 18:49:12,591  visitors_in_thread1/visitors_in_thread1.py:98  ip不可用：https://116.115.208.194:25495HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out')))
2019-07-28 18:49:19,700  visitors_in_thread1/visitors_in_thread1.py:98  ip不可用：https://27.204.77.240:38683HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out')))
